% 
% Comparison based on single unit acitivity
% 
% -------------------------------------------------------------------------
% version 1.0.4
% 
% 
% 
% Check all neurons stastical properity comparing to ephys
% 
addpath('../Func');
setDir;
load ([TempDatDir 'DataListShuffle.mat']);
fileList                 = {SpikeFileList; CaImagingShortDelayFastFileList; CaImagingShortDelaySlowFileList;...
                            CaImagingLongDelayFastFileList; CaImagingLongDelaySlowFileList; CaImagingShortDelaySlowVirusFileList};

nData                    = 1;
load([TempDatDir DataSetList(nData).name '.mat']);
ephysCellIndex{nData}        = [DataSetList(nData).cellinfo(:).depth]  > 120 &...
                           [DataSetList(nData).cellinfo(:).depth]  < 750 & ...
                           [DataSetList(nData).cellinfo(:).ML_axis]  > 1100 &...
                           [DataSetList(nData).cellinfo(:).ML_axis]  < 1900;                        
for nData           = 2:length(fileList)
    load([TempDatDir DataSetList(nData).name '.mat']);
    ephysCellIndex{nData}  = [DataSetList(nData).cellinfo(:).depth]  > 120 &...
                           [DataSetList(nData).cellinfo(:).depth]  < 750 & ...
                           [DataSetList(nData).cellinfo(:).AP_axis]  > 2450 &...
                           [DataSetList(nData).cellinfo(:).AP_axis]  < 2800 &...
                           [DataSetList(nData).cellinfo(:).ML_axis]  > 1100 &...
                           [DataSetList(nData).cellinfo(:).ML_axis]  < 1900;                        
end



nData           = 4;
load([TempDatDir DataSetList(nData).name '.mat']);
ephysCellIndex{nData}  = [DataSetList(nData).cellinfo(:).depth]  > 120 &...
                       [DataSetList(nData).cellinfo(:).depth]  < 750 & ...
                       [DataSetList(nData).cellinfo(:).AP_axis]  > 2450 &...
                       [DataSetList(nData).cellinfo(:).AP_axis]  < 2800 &...
                       [DataSetList(nData).cellinfo(:).ML_axis]  > 1100 &...
                       [DataSetList(nData).cellinfo(:).ML_axis]  < 1900;                        

nData           = 5;
load([TempDatDir DataSetList(nData).name '.mat']);
ephysCellIndex{nData}  = [DataSetList(nData).cellinfo(:).depth]  > 120 &...
                       [DataSetList(nData).cellinfo(:).depth]  < 750 & ...
                       [DataSetList(nData).cellinfo(:).AP_axis]  > 2450 &...
                       [DataSetList(nData).cellinfo(:).AP_axis]  < 2800 &...
                       [DataSetList(nData).cellinfo(:).ML_axis]  > 1100 &...
                       [DataSetList(nData).cellinfo(:).ML_axis]  < 1900;                   
                   

fileToAnalysis                = [1 4 5]; % 1:length(DataSetList);                   
save ([TempDatDir 'DataListShuffle.mat'], 'ephysCellIndex', 'fileList', 'fileToAnalysis', '-append');
