generateModeledDatasets
rawActivity
switchSelectivityDist   
FPVT
logPValueANOVA
rocEpochDist          
meanPCATraces
meanPCA                 
activityProfileChangeOnEpochsStats
noiseCorrelationEpochs
trialEpochLDATimeDelay
trialEpochLDA
trialTypeLDANum
trialLDA_LDA   
